<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Gyroscops\Api\Normalizer;

use Gyroscops\Api\Runtime\Normalizer\CheckArray;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class BigDecimalNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;

    public function supportsDenormalization($data, $type, $format = null): bool
    {
        return $type === \Gyroscops\Api\Model\BigDecimal::class;
    }

    public function supportsNormalization($data, $format = null): bool
    {
        return is_object($data) && $data::class === \Gyroscops\Api\Model\BigDecimal::class;
    }

    /**
     * @return mixed
     */
    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \Gyroscops\Api\Model\BigDecimal();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('scale', $data) && $data['scale'] !== null) {
            $object->setScale($data['scale']);
        } elseif (\array_key_exists('scale', $data) && $data['scale'] === null) {
            $object->setScale(null);
        }
        if (\array_key_exists('sign', $data) && $data['sign'] !== null) {
            $object->setSign($data['sign']);
        } elseif (\array_key_exists('sign', $data) && $data['sign'] === null) {
            $object->setSign(null);
        }
        if (\array_key_exists('unscaledValue', $data) && $data['unscaledValue'] !== null) {
            $object->setUnscaledValue($this->denormalizer->denormalize($data['unscaledValue'], \Gyroscops\Api\Model\BigInteger::class, 'json', $context));
        } elseif (\array_key_exists('unscaledValue', $data) && $data['unscaledValue'] === null) {
            $object->setUnscaledValue(null);
        }
        if (\array_key_exists('integralPart', $data) && $data['integralPart'] !== null) {
            $object->setIntegralPart($data['integralPart']);
        } elseif (\array_key_exists('integralPart', $data) && $data['integralPart'] === null) {
            $object->setIntegralPart(null);
        }
        if (\array_key_exists('fractionalPart', $data) && $data['fractionalPart'] !== null) {
            $object->setFractionalPart($data['fractionalPart']);
        } elseif (\array_key_exists('fractionalPart', $data) && $data['fractionalPart'] === null) {
            $object->setFractionalPart(null);
        }
        if (\array_key_exists('nonZeroFractionalPart', $data) && $data['nonZeroFractionalPart'] !== null) {
            $object->setNonZeroFractionalPart($data['nonZeroFractionalPart']);
        } elseif (\array_key_exists('nonZeroFractionalPart', $data) && $data['nonZeroFractionalPart'] === null) {
            $object->setNonZeroFractionalPart(null);
        }
        if (\array_key_exists('zero', $data) && $data['zero'] !== null) {
            $object->setZero($data['zero']);
        } elseif (\array_key_exists('zero', $data) && $data['zero'] === null) {
            $object->setZero(null);
        }
        if (\array_key_exists('negative', $data) && $data['negative'] !== null) {
            $object->setNegative($data['negative']);
        } elseif (\array_key_exists('negative', $data) && $data['negative'] === null) {
            $object->setNegative(null);
        }
        if (\array_key_exists('negativeOrZero', $data) && $data['negativeOrZero'] !== null) {
            $object->setNegativeOrZero($data['negativeOrZero']);
        } elseif (\array_key_exists('negativeOrZero', $data) && $data['negativeOrZero'] === null) {
            $object->setNegativeOrZero(null);
        }
        if (\array_key_exists('positive', $data) && $data['positive'] !== null) {
            $object->setPositive($data['positive']);
        } elseif (\array_key_exists('positive', $data) && $data['positive'] === null) {
            $object->setPositive(null);
        }
        if (\array_key_exists('positiveOrZero', $data) && $data['positiveOrZero'] !== null) {
            $object->setPositiveOrZero($data['positiveOrZero']);
        } elseif (\array_key_exists('positiveOrZero', $data) && $data['positiveOrZero'] === null) {
            $object->setPositiveOrZero(null);
        }

        return $object;
    }

    /**
     * @return array|string|int|float|bool|\ArrayObject|null
     */
    public function normalize($object, $format = null, array $context = [])
    {
        $data = [];
        if (null !== $object->getUnscaledValue()) {
            $data['unscaledValue'] = $this->normalizer->normalize($object->getUnscaledValue(), 'json', $context);
        }

        return $data;
    }
}
