<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Gyroscops\Api\Normalizer;

use Gyroscops\Api\Runtime\Normalizer\CheckArray;
use Gyroscops\Api\Runtime\Normalizer\ValidatorTrait;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class WorkspaceNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;
    use ValidatorTrait;

    public function supportsDenormalization($data, $type, $format = null, array $context = []): bool
    {
        return $type === 'Gyroscops\\Api\\Model\\Workspace';
    }

    public function supportsNormalization($data, $format = null, array $context = []): bool
    {
        return is_object($data) && get_class($data) === 'Gyroscops\\Api\\Model\\Workspace';
    }

    /**
     * @return mixed
     */
    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \Gyroscops\Api\Model\Workspace();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('id', $data) && $data['id'] !== null) {
            $object->setId($data['id']);
            unset($data['id']);
        } elseif (\array_key_exists('id', $data) && $data['id'] === null) {
            $object->setId(null);
        }
        if (\array_key_exists('name', $data) && $data['name'] !== null) {
            $object->setName($data['name']);
            unset($data['name']);
        } elseif (\array_key_exists('name', $data) && $data['name'] === null) {
            $object->setName(null);
        }
        if (\array_key_exists('slug', $data) && $data['slug'] !== null) {
            $object->setSlug($data['slug']);
            unset($data['slug']);
        } elseif (\array_key_exists('slug', $data) && $data['slug'] === null) {
            $object->setSlug(null);
        }
        if (\array_key_exists('organization', $data) && $data['organization'] !== null) {
            $object->setOrganization($data['organization']);
            unset($data['organization']);
        } elseif (\array_key_exists('organization', $data) && $data['organization'] === null) {
            $object->setOrganization(null);
        }
        if (\array_key_exists('region', $data) && $data['region'] !== null) {
            $value = $data['region'];
            if (is_array($data['region']) and isset($data['region']['provider']) and isset($data['region']['datacenterName']) and isset($data['region']['datacenterAddress'])) {
                $value = $this->denormalizer->denormalize($data['region'], 'Gyroscops\\Api\\Model\\Region', 'json', $context);
            }
            $object->setRegion($value);
            unset($data['region']);
        } elseif (\array_key_exists('region', $data) && $data['region'] === null) {
            $object->setRegion(null);
        }
        if (\array_key_exists('authorizations', $data) && $data['authorizations'] !== null) {
            $values = [];
            foreach ($data['authorizations'] as $value_1) {
                $values[] = $value_1;
            }
            $object->setAuthorizations($values);
            unset($data['authorizations']);
        } elseif (\array_key_exists('authorizations', $data) && $data['authorizations'] === null) {
            $object->setAuthorizations(null);
        }
        if (\array_key_exists('users', $data) && $data['users'] !== null) {
            $values_1 = [];
            foreach ($data['users'] as $value_2) {
                $values_1[] = $value_2;
            }
            $object->setUsers($values_1);
            unset($data['users']);
        } elseif (\array_key_exists('users', $data) && $data['users'] === null) {
            $object->setUsers(null);
        }
        foreach ($data as $key => $value_3) {
            if (preg_match('/.*/', (string) $key)) {
                $object[$key] = $value_3;
            }
        }

        return $object;
    }

    /**
     * @return array|string|int|float|bool|\ArrayObject|null
     */
    public function normalize($object, $format = null, array $context = [])
    {
        $data = [];
        $data['name'] = $object->getName();
        if ($object->isInitialized('slug') && null !== $object->getSlug()) {
            $data['slug'] = $object->getSlug();
        }
        $data['organization'] = $object->getOrganization();
        $value = $object->getRegion();
        if (is_object($object->getRegion())) {
            $value = $this->normalizer->normalize($object->getRegion(), 'json', $context);
        }
        $data['region'] = $value;
        if ($object->isInitialized('authorizations') && null !== $object->getAuthorizations()) {
            $values = [];
            foreach ($object->getAuthorizations() as $value_1) {
                $values[] = $value_1;
            }
            $data['authorizations'] = $values;
        }
        if ($object->isInitialized('users') && null !== $object->getUsers()) {
            $values_1 = [];
            foreach ($object->getUsers() as $value_2) {
                $values_1[] = $value_2;
            }
            $data['users'] = $values_1;
        }
        foreach ($object as $key => $value_3) {
            if (preg_match('/.*/', (string) $key)) {
                $data[$key] = $value_3;
            }
        }

        return $data;
    }
}
