<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Gyroscops\Api\Model;

class Composer extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var ComposerAutoload[]|null
     */
    protected $autoloads;
    /**
     * @var string[]|null
     */
    protected $packages;
    /**
     * @var ComposerRepository[]|null
     */
    protected $repositories;
    /**
     * @var ComposerAuthentication[]|null
     */
    protected $authentications;

    /**
     * @return ComposerAutoload[]|null
     */
    public function getAutoloads(): ?array
    {
        return $this->autoloads;
    }

    /**
     * @param ComposerAutoload[]|null $autoloads
     */
    public function setAutoloads(?array $autoloads): self
    {
        $this->initialized['autoloads'] = true;
        $this->autoloads = $autoloads;

        return $this;
    }

    /**
     * @return string[]|null
     */
    public function getPackages(): ?iterable
    {
        return $this->packages;
    }

    /**
     * @param string[]|null $packages
     */
    public function setPackages(?iterable $packages): self
    {
        $this->initialized['packages'] = true;
        $this->packages = $packages;

        return $this;
    }

    /**
     * @return ComposerRepository[]|null
     */
    public function getRepositories(): ?array
    {
        return $this->repositories;
    }

    /**
     * @param ComposerRepository[]|null $repositories
     */
    public function setRepositories(?array $repositories): self
    {
        $this->initialized['repositories'] = true;
        $this->repositories = $repositories;

        return $this;
    }

    /**
     * @return ComposerAuthentication[]|null
     */
    public function getAuthentications(): ?array
    {
        return $this->authentications;
    }

    /**
     * @param ComposerAuthentication[]|null $authentications
     */
    public function setAuthentications(?array $authentications): self
    {
        $this->initialized['authentications'] = true;
        $this->authentications = $authentications;

        return $this;
    }
}
