<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Gyroscops\Api\Model;

class ReferralCodeReferralCodeRead extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var string|null
     */
    protected $id;
    /**
     * @var string|null
     */
    protected $user;
    /**
     * @var string|null
     */
    protected $code;
    /**
     * @var string[]|null
     */
    protected $referralRequests;

    public function getId(): ?string
    {
        return $this->id;
    }

    public function setId(?string $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;

        return $this;
    }

    public function getUser(): ?string
    {
        return $this->user;
    }

    public function setUser(?string $user): self
    {
        $this->initialized['user'] = true;
        $this->user = $user;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(?string $code): self
    {
        $this->initialized['code'] = true;
        $this->code = $code;

        return $this;
    }

    /**
     * @return string[]|null
     */
    public function getReferralRequests(): ?array
    {
        return $this->referralRequests;
    }

    /**
     * @param string[]|null $referralRequests
     */
    public function setReferralRequests(?array $referralRequests): self
    {
        $this->initialized['referralRequests'] = true;
        $this->referralRequests = $referralRequests;

        return $this;
    }
}
