<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Gyroscops\Api\Model;

class SubscriptionOfferWrite extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var int|null
     */
    protected $rank;
    /**
     * @var bool|null
     */
    protected $active;
    /**
     * @var \DateTime|null
     */
    protected $activeFrom;
    /**
     * @var \DateTime|null
     */
    protected $activeUntil;

    public function getRank(): ?int
    {
        return $this->rank;
    }

    public function setRank(?int $rank): self
    {
        $this->initialized['rank'] = true;
        $this->rank = $rank;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(?bool $active): self
    {
        $this->initialized['active'] = true;
        $this->active = $active;

        return $this;
    }

    public function getActiveFrom(): ?\DateTime
    {
        return $this->activeFrom;
    }

    public function setActiveFrom(?\DateTime $activeFrom): self
    {
        $this->initialized['activeFrom'] = true;
        $this->activeFrom = $activeFrom;

        return $this;
    }

    public function getActiveUntil(): ?\DateTime
    {
        return $this->activeUntil;
    }

    public function setActiveUntil(?\DateTime $activeUntil): self
    {
        $this->initialized['activeUntil'] = true;
        $this->activeUntil = $activeUntil;

        return $this;
    }
}
