<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Gyroscops\Api\Model;

class UserId extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var bool|null
     */
    protected $nil;

    public function getNil(): ?bool
    {
        return $this->nil;
    }

    public function setNil(?bool $nil): self
    {
        $this->initialized['nil'] = true;
        $this->nil = $nil;

        return $this;
    }
}
